import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import "./styles/crt-effect.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nigel Mckenzie-Ryan - Software Developer",
  description: "Generated by create next app",
  metadataBase: new URL("https://mckenryan.work/"),
  openGraph: {
    siteName: "Nigel Mckenzie-Ryan - Software Developer",
    locale: "en_AU",
    type: "website",
    images: [
      {
        url: "/public/static/headshots/cropped.webp",
        width: 400,
        height: 400,
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: "index, follow",
  },
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        type: "image/x-icon",
      },
      {
        url: "/android-chrome-192x192.png",
        type: "image/png",
        sizes: "192x192",
      },
      {
        url: "/android-chrome-512x512.png",
        type: "image/png",
        sizes: "512x512",
      },
      {
        url: "/favicon-32x32.png",
        type: "image/png",
        sizes: "32x32",
      },
      {
        url: "/favicon-16x16.png",
        type: "image/png",
        sizes: "16x16",
      },
      {
        url: "/site.webmanifest",
        type: "application/manifest+json",
      },
      {
        url: "/apple-touch-icon.png",
        type: "image/png",
        sizes: "180x180",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen`}
      >
        {/* Background */}
        <div className="fixed inset-0 bg-[url('../public/wallpaper_small.webp')] bg-center"></div>

        {/* 70s TV Vignette */}
        <div
          className="fixed inset-0"
          style={{
            background: `radial-gradient(
              circle at center,
              transparent 0%,
              rgba(0, 0, 0, 0.7) 70%,
              rgba(0, 0, 0, 0.9) 100%
            )`,
            boxShadow: "inset 0 0 10px rgba(0, 0, 0, 0.8)",
            zIndex: 1,
            pointerEvents: "none",
          }}
        >
          {/* CRT Scanlines */}
          <div
            className="absolute inset-0"
            style={{
              backgroundImage: `repeating-linear-gradient(
                to bottom,
                rgba(0, 0, 0, 0.1) 0px,
                rgba(0, 0, 0, 0.1) 1px,
                transparent 1px,
                transparent 2px
              )`,
              opacity: 0.5,
              zIndex: 2,
            }}
          />{" "}
        </div>
        {/* Content */}
        <div className="relative z-10 min-h-screen">{children}</div>
      </body>
    </html>
  );
}
