import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nigel Mckenzie-Ryan - Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen`}
      >
        {/* Background */}
        <div className="fixed inset-0 bg-[url('../public/wallpaper_small.webp')] bg-center"></div>

        {/* Content */}
        <div className="relative z-10 min-h-screen">{children}</div>
      </body>
    </html>
  );
}
